### ISSUE TITLE
Number of rects does not mach number of Nodes

### ISSUE THREAD

**Issue by vijay-online-bub** [wildhaber/haar2tjs#1]
Hi,

I am facing issue when i am trying to convert haarcascade_eye_tree_eyeglasses.xml from opencv haar classifier.Can you please tell me what to do.

**Comment by wildhaber** [comment]
Hi @vijay-online-bub,

Thanks for the notice. I have converted this exception into a simple console log instead of letting the process fail.

You can find the changes in the version v0.1.1.
- Package: https://www.npmjs.com/package/haar2tjs
