### ISSUE TITLE
Error installing (node-gyp)

### ISSUE THREAD

**Issue by Sithdown** [wildhaber/haar2tjs#2]
> npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

Windows 10 x64

**Comment by wildhaber** [comment]
Hey @Sithdown , this is most probably not an issue with this package.

For further information: https://github.com/nodejs/node-gyp#on-windows

The related project `iconv` you can find here:
https://github.com/bnoordhuis/node-iconv

**Comment by quitequinn** [comment]
@Sithdown Did you solve this? Having the same issue.

**Comment by NateBrown101** [comment]
same issue here
